// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkwSXnHZro3N4-L-sjQaqCsCaqxn9mDak',
    appId: '1:302902735981:web:61194ddddd1d1180543b64',
    messagingSenderId: '302902735981',
    projectId: 'fitnessplanner-88',
    authDomain: 'fitnessplanner-88.firebaseapp.com',
    storageBucket: 'fitnessplanner-88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDpH3NFpUi0qhl-eC22NKH3Pr-70YIBbU',
    appId: '1:302902735981:android:fa32100214174d9a543b64',
    messagingSenderId: '302902735981',
    projectId: 'fitnessplanner-88',
    storageBucket: 'fitnessplanner-88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1oNZ_xJ-bGw06K0xTVLeAiGtvqwXeWKI',
    appId: '1:302902735981:ios:963c43ef409ff4ca543b64',
    messagingSenderId: '302902735981',
    projectId: 'fitnessplanner-88',
    storageBucket: 'fitnessplanner-88.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1oNZ_xJ-bGw06K0xTVLeAiGtvqwXeWKI',
    appId: '1:302902735981:ios:963c43ef409ff4ca543b64',
    messagingSenderId: '302902735981',
    projectId: 'fitnessplanner-88',
    storageBucket: 'fitnessplanner-88.firebasestorage.app',
    iosBundleId: 'com.example.fitnessPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkwSXnHZro3N4-L-sjQaqCsCaqxn9mDak',
    appId: '1:302902735981:web:96b46421c1d47d12543b64',
    messagingSenderId: '302902735981',
    projectId: 'fitnessplanner-88',
    authDomain: 'fitnessplanner-88.firebaseapp.com',
    storageBucket: 'fitnessplanner-88.firebasestorage.app',
  );

}